In [2]:
import numpy as np

In [1]:
data = [1, 2, 3, 4]
data * 10

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [5]:
arr = np.array(data)
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(data)

list

In [9]:
arr * 10

array([10, 20, 30, 40])

In [10]:
price = [
    [100, 80, 70, 90],
    [1, 2, 3, 4]
]
type(price)

list

In [12]:
price[0]

[100, 80, 70, 90]

In [14]:
arr = np.array(price)
arr

array([[100,  80,  70,  90],
       [  1,   2,   3,   4]])

In [15]:
arr[0]

array([100,  80,  70,  90])

In [16]:
arr[1]

array([1, 2, 3, 4])

In [17]:
arr[0][0]

np.int64(100)

In [18]:
arr[0,0]

np.int64(100)

In [19]:
arr[:, 0]

array([100,   1])

In [20]:
arr[:, 2]

array([70,  3])